GET http://megafon/api/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYjJhZTYzODdlMTBhMDY4YTE3YTI1NGRhMzg1YzJmMzlkOGZjNDgxNTE0NTRjODM2ZGI1YThhOTMzM2U3MThmOWEyYjVjN2ZiZjMxOWFlNzYiLCJpYXQiOjE1OTgzNTk1NTEsIm5iZiI6MTU5ODM1OTU1MSwiZXhwIjoxNjI5ODk1NTUxLCJzdWIiOiIxIiwic2NvcGVzIjpbIkFETUlOIl19.ekgfwFSEEFghQEGK7Ek1QJMTLxWceM-xwkSa7YKyVQk2VdPOS05oa5dnL8bEF4_abK-7cxgZiPLaA7O9N5STVBj9N68JnlA13iGYqGZiFtRyMUklbYJcoZf2ArsC6gGO-XLio9rza2I-bQUK3y5kaSj79FeJfUNfm-3msLDqtTYjPSj_Y7Miro0PgyUi7NkNvX_v7R-1z2B9J15F6QRweT21J5p94G_iT6riFw-2SjLku9yLgLIU9s9QYXoVfxNTYahAZb0zMUhGDIk8rByd38-DVnCVjpF6gn6T3cSFeCSWBHnqxM22HM6es5HtW9lUhBSDUCFDeMMToGB30scOKSxrAXohi2O2iepkHi9EVEJD7V8DI3P9EyNXouNyBWGo1-QIrKvjTvDjHzUYl9lGJ9TC2CEvcdlkybVI1eckwSh4p2NLOcxizeHuiv_PcIWabPcUD1Bs-YS8Heu8eEHmO3Kic0wd0qBWaRgFjgX8F_6Mke07RAYbl2EYkAo5s9yX6PEHhMANJBy1wpJoG2RBe-yWgH4rYYivZ4V5v-0L8X75cEDnxodO4PkHDkqY9fTgTichhzqLi3pe2i_3__KpO1-GJEpL58x7QINhDWWhA1czZp5lZGEBb4rncmkJxSKNKh9-hFez8SXVz3Yd7WXSKIDhlbqGMavi1ePkFU_4U1o

###
